# Subscriber
car_state_topic_name: /estimation/slam/state

transform_matrix_topic_name: /transform_matrix

# Publisher
ctrl_cmd_topic_name: /control/pure_pursuit/control_command

# MPC params:
weight:
  px: 1.5
  py: 1.5
  pyaw: 8
  cte: 1
  epsi: 4
  v: 0.4
  steer: 4
  throttle: 10
  steer_rate: 2000
  throttle_rate: 10
  desire_vel: 15

# Pure Pursuit params:
desire_vel: 3.0

car_length: 1.88

look_ahead: 20

# Track params:
interval: 0.05

forward_distance: 15.0

circle_radius: 9.125

max_lat_acc: 3.0



# other params:
N: 40

dt: 0.04

initial_velocity: 2

mission: skidpad          # [trackdrive, skidpad, acceleration]

controller: mpc  # [mpc, pure_pursuit]

simulation: true

node_rate: 100   # [Herz]
