cluster_filtered_topic_name: /perception/lidar_cluster

transform_matrix_topic_name: /transform_matrix

path:
  skidpad_map: /home/feng1909/fsd_algorithm/ros/planning/skidpad_detector/config/skidpad.pcd
  path_x: /home/feng1909/fsd_algorithm/ros/planning/skidpad_detector/config/path_x.txt
  path_y: /home/feng1909/fsd_algorithm/ros/planning/skidpad_detector/config/path_y.txt

length:
  start: 15.0
  lidar2imu: 1.87
  threshold: 0.7

node_rate: 50   # [Herz]
